// frontend-react/src/app/WorkbenchLayout.tsx
import { NavLink, Outlet } from "react-router-dom";

const navItems = [
  { to: "/chat", label: "Chat", icon: "chat" },
  { to: "/knowledge-base", label: "Knowledge Base", icon: "database" },
  { to: "/documents", label: "Documents", icon: "description" },
  { to: "/experiments", label: "Experiments", icon: "science" },
  { to: "/graph", label: "Graph", icon: "account_tree" },
  { to: "/feedback", label: "Feedback", icon: "rate_review" },
  { to: "/settings", label: "Settings", icon: "settings" }
];

export function WorkbenchLayout(): JSX.Element {
  return (
    <div className="workbench-shell">
      <aside className="side-nav">
        <div className="brand-block">
          <strong>Workbench</strong>
          <span>React rebuild</span>
        </div>
        <nav>
          {navItems.map((item) => (
            <NavLink
              key={item.to}
              to={item.to}
              className={({ isActive }) => `side-nav-link${isActive ? " is-active" : ""}`}
            >
              <span className="material-symbols">{item.icon}</span>
              <span>{item.label}</span>
            </NavLink>
          ))}
        </nav>
      </aside>
      <div className="workbench-main">
        <header className="top-bar">
          <div>
            <strong>RAG Workbench</strong>
            <span>Experiment Explorer</span>
          </div>
          <NavLink className="comparison-link" to="/experiments/comparison">
            策略对比
          </NavLink>
        </header>
        <main className="content-scroll">
          <Outlet />
        </main>
      </div>
    </div>
  );
}

// frontend/src/layouts/WorkbenchLayout.vue
﻿<template>
  <div class="shell">
    <aside class="sidebar">
      <div class="brand-block">
        <div class="brand-logo">K</div>
        <div class="brand-title">Knowledge Base</div>
        <div class="brand-subtitle">Vue 3 + Spring Boot + FastAPI</div>
      </div>

      <nav class="nav-list">
        <RouterLink
          v-for="item in navigation"
          :key="item.to"
          :to="item.to"
          class="nav-link"
        >
          {{ item.label }}
        </RouterLink>
      </nav>

      <div class="sidebar-footer">
        <strong>接口约束</strong>
        <span>页面不直接请求后端，统一经由 src/api/。</span>
      </div>
    </aside>

    <div class="main">
      <header class="topbar">
        <div>
          <h1 class="page-title">{{ currentTitle }}</h1>
          <p class="page-subtitle">{{ currentSubtitle }}</p>
        </div>
        <div class="topbar-actions">
          <span class="status-pill status-muted">Trace {{ store.traceId }}</span>
          <span class="status-pill status-success">{{ store.selectedStrategy }}</span>
        </div>
      </header>

      <main class="content">
        <RouterView />
      </main>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted } from "vue";
import { RouterLink, RouterView, useRoute } from "vue-router";
import type { NavigationItem } from "../types";
import { useWorkbenchStore } from "../stores/workbench";

const route = useRoute();
const store = useWorkbenchStore();

const navigation: NavigationItem[] = [
  { label: "对话工作台", to: "/chat", description: "问答与引用来源" },
  { label: "文档中心", to: "/documents", description: "上传与处理状态" },
  { label: "知识库", to: "/knowledge-base", description: "知识库概览" },
  { label: "实验评估", to: "/experiments", description: "策略对比" },
  { label: "评估对比", to: "/experiments/comparison", description: "RAG 评估聚合" },
  { label: "图谱事实", to: "/graph", description: "实体与关系" },
  { label: "用户反馈", to: "/feedback", description: "提交与查看反馈" },
  { label: "系统设置", to: "/settings", description: "接口和默认参数" },
];

const currentTitle = computed(() => String(route.meta.title ?? "工作台"));
const currentSubtitle = computed(() => String(route.meta.subtitle ?? "本地知识库问答与文档管理"));

onMounted(() => {
  void store.hydrate();
});
</script>
