// frontend-react/src/pages/SettingsPage.tsx
import { Save } from "lucide-react";
import { useEffect, useState } from "react";
import { API_RUNTIME_SETTINGS_KEY, fetchSettings } from "../api";
import { Button } from "../components/primitives/Button";
import { Panel } from "../components/primitives/Panel";
import type { AppSettings } from "../types";
import "./pages.css";

const fallbackSettings: AppSettings = {
  apiBaseUrl: "/api",
  aiServiceBaseUrl: "",
  defaultKnowledgeBaseId: "",
  timeoutMs: 15000,
  includeTraceHeader: true
};

function loadLocal(): AppSettings {
  try {
    const raw = window.localStorage.getItem(API_RUNTIME_SETTINGS_KEY);
    return raw ? { ...fallbackSettings, ...JSON.parse(raw) } : fallbackSettings;
  } catch {
    return fallbackSettings;
  }
}

export function SettingsPage() {
  const [settings, setSettings] = useState<AppSettings>(loadLocal);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");

  useEffect(() => {
    fetchSettings()
      .then((remote) => setSettings((current) => ({ ...current, ...remote })))
      .catch(() => {
        setError("后端设置接口不可用，当前展示本地运行时配置。");
      });
  }, []);

  function update<K extends keyof AppSettings>(key: K, value: AppSettings[K]) {
    setSettings((current) => ({ ...current, [key]: value }));
  }

  function save() {
    window.localStorage.setItem(API_RUNTIME_SETTINGS_KEY, JSON.stringify(settings));
    setMessage("设置已保存到浏览器本地。");
  }

  return (
    <div className="page-canvas page-stack">
      <header className="page-header">
        <div>
          <h2>Settings</h2>
          <p>这些配置只影响前端运行时请求，浏览器仍通过 Spring Boot `/api/*` 进入后端。</p>
        </div>
      </header>
      {error ? <div className="alert-error">{error}</div> : null}
      {message ? <div className="alert-success">{message}</div> : null}
      <Panel title="运行时 API 设置">
        <div className="stacked-form">
          <label><span>API Base URL</span><input value={settings.apiBaseUrl} onChange={(event) => update("apiBaseUrl", event.target.value)} /></label>
          <label><span>默认知识库 ID</span><input value={settings.defaultKnowledgeBaseId} onChange={(event) => update("defaultKnowledgeBaseId", event.target.value)} /></label>
          <label><span>请求超时 ms</span><input type="number" value={settings.timeoutMs} onChange={(event) => update("timeoutMs", Number(event.target.value))} /></label>
          <label className="checkbox-row">
            <input type="checkbox" checked={settings.includeTraceHeader} onChange={(event) => update("includeTraceHeader", event.target.checked)} />
            <span>发送 X-Trace-Id 请求头</span>
          </label>
          <Button icon={<Save />} variant="primary" onClick={save}>保存设置</Button>
        </div>
      </Panel>
    </div>
  );
}

// frontend/src/pages/settings/SettingsPage.vue
<template>
  <div class="page-grid">
    <section class="panel">
      <div class="panel-header">
        <h2 class="panel-title">系统设置</h2>
        <p class="panel-subtitle">本地配置项保存于浏览器本地存储，无需后端持久化接口。</p>
      </div>
      <div class="panel-body">
        <div class="form-grid">
          <label class="form-row">
            <span class="form-label">API Base URL</span>
            <input v-model="local.apiBaseUrl" class="input" placeholder="/api" />
          </label>
          <label class="form-row">
            <span class="form-label">AI Service Base URL</span>
            <input v-model="local.aiServiceBaseUrl" class="input" placeholder="http://localhost:8001" />
          </label>
          <label class="form-row">
            <span class="form-label">默认知识库</span>
            <select v-model="local.defaultKnowledgeBaseId" class="input">
              <option value="">— 未选择 —</option>
              <option v-for="kb in store.knowledgeBases" :key="kb.id" :value="kb.id">
                {{ kb.name }}
              </option>
            </select>
          </label>
          <label class="form-row">
            <span class="form-label">请求超时 (ms)</span>
            <input v-model.number="local.timeoutMs" class="input" type="number" min="1000" max="60000" step="1000" />
          </label>
          <label class="form-row" style="flex-direction: row; align-items: center; gap: 0.75rem;">
            <input v-model="local.includeTraceHeader" type="checkbox" />
            <span class="form-label">附带 X-Trace-Id 请求头</span>
          </label>
          <div class="tag-row">
            <span class="tag">统一 API Client</span>
            <span class="tag">Trace Header</span>
            <span class="tag">本地持久化</span>
          </div>
          <div class="button-row">
            <button class="button button-primary" type="button" @click="saveSettings">
              保存设置
            </button>
            <span v-if="saved" class="item-meta" style="margin-left: 0.75rem;">已保存</span>
          </div>
          <div v-if="store.lastError" class="empty-state">{{ store.lastError }}</div>
        </div>
      </div>
    </section>
  </div>
</template>

<script setup lang="ts">
import { reactive, ref, watch } from "vue";
import { useWorkbenchStore } from "../../stores/workbench";
import { API_RUNTIME_SETTINGS_KEY } from "../../api";

const STORAGE_KEY = API_RUNTIME_SETTINGS_KEY;

const store = useWorkbenchStore();
const saved = ref(false);

const persistedSettings = (() => {
  try {
    return JSON.parse(localStorage.getItem(STORAGE_KEY) ?? "{}") as Partial<typeof store.settings>;
  } catch {
    return {};
  }
})();

const local = reactive({
  apiBaseUrl: persistedSettings.apiBaseUrl ?? store.settings.apiBaseUrl,
  aiServiceBaseUrl: persistedSettings.aiServiceBaseUrl ?? store.settings.aiServiceBaseUrl,
  defaultKnowledgeBaseId: persistedSettings.defaultKnowledgeBaseId ?? store.settings.defaultKnowledgeBaseId,
  timeoutMs: persistedSettings.timeoutMs ?? store.settings.timeoutMs,
  includeTraceHeader: persistedSettings.includeTraceHeader ?? store.settings.includeTraceHeader,
});

Object.assign(store.settings, local);

// 拉取到新 settings 时同步到本地表单
watch(() => store.settings, (s) => {
  local.apiBaseUrl = s.apiBaseUrl;
  local.aiServiceBaseUrl = s.aiServiceBaseUrl;
  local.defaultKnowledgeBaseId = s.defaultKnowledgeBaseId;
  local.timeoutMs = s.timeoutMs;
  local.includeTraceHeader = s.includeTraceHeader;
}, { deep: true });

function saveSettings(): void {
  const payload = {
    apiBaseUrl: local.apiBaseUrl,
    aiServiceBaseUrl: local.aiServiceBaseUrl,
    defaultKnowledgeBaseId: local.defaultKnowledgeBaseId,
    timeoutMs: local.timeoutMs,
    includeTraceHeader: local.includeTraceHeader,
  };
  store.settings.apiBaseUrl = payload.apiBaseUrl;
  store.settings.aiServiceBaseUrl = payload.aiServiceBaseUrl;
  store.settings.defaultKnowledgeBaseId = payload.defaultKnowledgeBaseId;
  store.settings.timeoutMs = payload.timeoutMs;
  store.settings.includeTraceHeader = payload.includeTraceHeader;
  localStorage.setItem(STORAGE_KEY, JSON.stringify(payload));
  saved.value = true;
  setTimeout(() => { saved.value = false; }, 2000);
}
</script>
